version: '3.8'

services:
  api:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: mooc-api-server
    restart: always
    ports:
      - "80:8080"
      - "8080:8080"
    env_file:
      - web-server.env
