version: '3.8'

services:
  worker:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: mooc-worker-server
    command: ["/app/worker"]
    restart: always
    env_file:
      - worker-server.env
